name=canpoint
version=0.0.1
author=Nick Locke <nick.locke@21jubileepark.com>
maintainer=Nick Locke <nick.locke@21jubileepark.com>
sentence=Point control for Roxeter panel
paragraph=
category=Communication
url=https://github.com/NickLocke/CANPOINT
architectures=*
includes=
depends=Streaming,ACAN2515
